# Generated by Django 5.0 on 2023-12-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='topic',
            new_name='blogger',
        ),
    ]
